amd-snowyowl-64: don't remove qemu-usermode from MACHINE_FEATURES
Issue: LINUXEXEC-33223

Since oe-core commit 86941419ef2d ("python3-pygobject: add explicit
check for qemu-usermode MACHINE_FEATURE"), qemu-usermode is needed
for python3-pygobject.

Fix the following error:

  ERROR: Nothing PROVIDES 'python3-pygobject'
  python3-pygobject was skipped: GI not available

Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>